config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  root "exams#index"
  devise_for :users

  resources :users, only: [:show] do
    resources :questions
  end

  resources :exams, except: [:new, :destroy, :edit]

  namespace :admin do
    root "users#index"
    resources :users, except: :show
    resources :subjects, except: [:show, :new]
    resources :exams, only: [:index]
    resources :admin_logs, only: [:index]
    resources :questions
    resources :suggested_questions, only: [:index]
  end

  mount Sidekiq::Web, at: "/sidekiq"
  mount DelayedJobWeb => "/delayed_job"
end

app/models/question.rb
class Question < ActiveRecord::Base
  acts_as_paranoid

  include PublicActivity::Common

  enum question_type: [:single, :multiple, :text]
  enum state: [:waiting, :accept, :refuse]

  has_many :answers, dependent: :destroy
  accepts_nested_attributes_for :answers, allow_destroy: true,
    reject_if: proc {|answer| answer[:content].blank?}
  has_many :results, dependent: :destroy

  belongs_to :subject
  belongs_to :user

  validates :content, presence: true

  private
  def answers_count_valid?
    answers.count >= Settings.answers_count_min
  end

  def check_answers_count
    unless answers_count_valid?
      errors.add :answers, I18n.t("errors.answers_count_not_valid")
    end
  end
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < ApplicationController
  load_and_authorize_resource
  before_action :load_subjects, only: [:new, :edit]
  before_action :build_answers, only: [:new]

  def index
    @search = @questions.accept.search params[:q]
    @questions = @search.result.paginate(page: params[:page]).includes(:subject)
    @activities = Questions::QuestionActivityService.list_activities.includes(:owner, :trackable)
  end

  def show
  end

  def new
  end

  def create
    if @question.save
      flash[:success] = t "user.question.create_success"
      redirect_to admin_questions_path
    else
      load_subjects
      build_answers
      render :new
    end
  end

  def edit
  end

  def update
    if params[:state].present?
      check_question params[:state]
    else
      update_question
    end
  end

  def destroy
    @question.destroy
    flash[:success] = t "user.question.delete_success"
    @question.create_activity :destroy, owner: current_user
    redirect_to admin_questions_path
  end

  private
  def question_params
    params.require(:question).permit :question_type, :content, :subject_id,
      :user_id, :state, answers_attributes: [:id,
      :correct, :content, :_destroy]
  end

  def build_answers
    @question.answers.reset
    @question.answers.build
  end

  def load_subjects
    @subjects = Subject.all
  end

  def check_question state
    if @question.update_attributes state: state, accepted_by: current_user.id
      flash[:success] = t "user.question.check_success"
      QuestionMailer.check_question(@question).deliver_now
    else
      flash[:danger] = t "user.question.check_fail"
    end
    redirect_to admin_suggested_questions_path
  end

  def update_question
    if @question.update_attributes question_params
      flash[:success] = t "user.question.update_success"
      @question.create_activity :update, owner: current_user
      redirect_to admin_questions_path
    else
      load_subjects
      render :edit
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  load_and_authorize_resource
  before_action :load_user, only: [:index]
  before_action :load_subjects, only: [:new]

  def index
    @questions = @user.questions
  end

  def new
  end

  def create
    if @question.save
      flash[:success] = t "user.question.create_success"
      @question.create_activity :create, owner: current_user
      redirect_to :back
    else
      load_subjects
      render :new
    end
  end

  def edit
    @subjects = Subject.all
  end

  def show
  end

  def update
    if @question.update_attributes question_params
      flash[:success] = t "user.question.update_success"
      @question.create_activity :update, owner: current_user
      redirect_to user_questions_path current_user
    else
      @subjects = Subject.all
      render :edit
    end
  end

  def destroy
    @question.destroy
    flash[:success] = t "user.question.delete_success"
    @question.create_activity :destroy, owner: current_user
    redirect_to user_questions_path current_user
  end

  private
  def question_params
    params.require(:question).permit :question_type, :content, :subject_id,
      :user_id, :state, answers_attributes: [:id,
      :correct, :content, :_destroy]
  end

  def load_user
    @user = User.find params[:user_id]
  end

  def load_subjects
    @question.answers.reset
    @question.answers.build
    @subjects = Subject.all
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_state question
    case question.state
    when "waiting"
      "<span class='label label-info'>#{question.state}</span>".html_safe
    when "accept"
      "<span class='label label-success'>#{question.state}</span>".html_safe
    when "refuse"
      "<span class='label label-danger'>#{question.state}</span>".html_safe
    end
  end
end

app/views/questions/_question.html.erb
<tr>
  <td><%= question.id %></td>
  <td><%= link_to question.content, user_question_path(@user, question) %></td>
  <td><%= question.subject.name %></td>
  <td><%= question.question_type %></td>
  <td><%= question_state question %></td>
  <td>
    <% if @user == current_user %>
      <div class="pull-right">
        <%= link_to "", edit_user_question_path(@user, question),
          class: "glyphicon glyphicon-pencil btn btn-sm btn-info" %>
        <%= link_to "", [@user, question], method: :delete,
          data: {confirm: t("you_sure")},
          class: "glyphicon glyphicon-trash btn btn-sm btn-danger" %>
      </div>
    <% end %>
  </td>
</tr>

app/views/questions/_question_form.html.erb
<%= form_for [current_user, @question] do |f| %>
  <%= render "shared/error_messages", object: @question %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.hidden_field :state, value: :waiting %>

  <%= f.label :subject %>
  <%= f.select :subject_id,
    options_from_collection_for_select(@subjects, :id, :name, params[:subject_id]),
    {}, {class: "form-control"} %>

  <%= f.label :content %>
  <%= f.text_area :content, class: "form-control" %>

  <%= f.label :question_type %>
  <%= f.select :question_type, Question.question_types.keys.to_a, {selected: :single},
    {class: "form-control width-question-type select-box"} %>

  <%= f.label :answer %>
  <div class="choise">
    <%= link_to_add_fields t("add_field"), f, :answers %>
    <%= f.fields_for :answers do |answer| %>
      <%= render "answer_fields", f: answer %>
    <% end %>
  </div>

  <div id="text">
    <%= f.fields_for :answers do |answer| %>
      <%= answer.text_field :content, class: "form-control" %>
    <% end %> 
  </div>

  <%= f.submit t("user.question.submit"), class: "btn btn-primary col-md-3" %>
<% end %>

app/views/questions/index.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <h2>
      <%= t "user.question.suggested" %>
      <%= link_to "", new_user_question_path(current_user),
        class: "pull-right glyphicon glyphicon-plus-sign" %>
    </h2>

    <table class="table table-hover"> 
      <thead class="thead-inverse">
        <tr> 
          <th>#</th> 
          <th><%= t "user.question.question" %></th> 
          <th><%= t "user.question.subject" %></th> 
          <th><%= t "user.question.type" %></th> 
          <th><%= t "user.question.state" %></th> 
          <th></th>
        </tr>
      </thead>
      <tbody>
        <ul class="questions">
          <%= render @questions %>
        </ul>
      </tbody>
    </table>
  </div>
</div>

app/views/questions/new.html.erb
<br>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <h2><%= t "user.question.new" %></h2>
    <%= render "question_form" %>
  </div>
</div>

app/views/questions/show.html.erb
<div class="row">
  <div class="col-md-5 col-md-offset-2">
    <h2>
      <%= t "user.question.question" %>
    </h2>

    <table class="table table-hover"> 
      <tbody>
        <tr>
          <th scope="row"><%= t "user.question.content" %></th>
          <td><%= @question.content %></td>
        </tr>

        <tr>
          <th scope="row"><%= t "user.question.answer" %></th>
          <td>
            <table>
              <tbody>
                <% @question.answers.each do |answer| %>
                <tr>
                  <td>
                    <span class="label label-<%= answer.correct ? 'success' : 'danger' %>">
                      <%= answer.correct %>
                    </span>
                  </td>
                  <td><%= answer.content %></td>
                </tr>
                <% end %>
              </tbody>
            </table>
          </td>
        </tr>

        <tr>
          <th scope="row"><%= t "user.question.subject" %></th>
          <td><%= @question.subject.name %></td>
        </tr>

        <tr>
          <th scope="row"><%= t "user.question.type" %></th>
          <td><%= @question.question_type %></td>
        </tr>

        <tr>
          <th scope="row"><%= t "user.question.state" %></th>
          <td>	<%= question_state @question %></td>
        </tr>
      </tbody>
    </table>

    <div class="row">
      <%= link_to t("user.question.edit"), edit_user_question_path(current_user, @question),
        class: "btn btn-info glyphicon glyphicon-pencil" %>
      <%= link_to t("user.question.delete"), [current_user, @question], method: :delete,
        data: {confirm: t("you_sure")}, class: "btn btn-danger glyphicon glyphicon-trash" %>
    </div>
  </div>
</div>