config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  root "exams#index"
  devise_for :users

  resources :users, only: [:show] do
    resources :questions
  end

  resources :exams, except: [:new, :destroy, :edit]

  namespace :admin do
    root "users#index"
    resources :users, except: :show
    resources :subjects, except: [:show, :new]
    resources :exams, only: [:index]
    resources :admin_logs, only: [:index]
    resources :questions
    resources :suggested_questions, only: [:index]
  end

  mount Sidekiq::Web, at: "/sidekiq"
  mount DelayedJobWeb => "/delayed_job"
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  acts_as_paranoid

  has_many :exams
  has_many :questions, dependent: :destroy

  validates :duration, numericality: true
  validates :question_num, numericality: [only_integer: true]
  validates :name, presence: true
end

app/controllers/admin/subjects_controller.rb
class Admin::SubjectsController < ApplicationController
  load_and_authorize_resource

  def index
    @subject = Subject.new
  end

  def create
    respond_to do |format|
      if @subject.save
        CreateSubjectWorker.perform_async @subject.id
        format.html do
          flash[:success] = t ".success"
          redirect_to admin_subjects_path
        end
      end
      format.js
    end
  end

  def edit
  end

  def update
    if @subject.update_attributes subject_params
      flash[:success] = t ".success"
      redirect_to admin_subjects_path
    else
      render :edit
    end
  end

  def destroy
    @subject.destroy
    flash[:success] = t ".success"
    redirect_to admin_subjects_path
  end

  private
  def subject_params
    params.require(:subject).permit :name, :description, :duration, :question_num
  end
end

app/helpers/subjects_helper.rb
module SubjectsHelper
  def status_button exam
    if exam.unstart?
      link_to t(:start), exam, class: "btn btn-primary"
    else
      link_to t(:view), exam, class: "btn btn-success"
    end
  end

  def format_score exam
    if exam.score.nil?
      "-"
    else
      "#{exam.score}/#{exam.question_num}".html_safe
    end
  end
end

app/views/admin/subjects/_form.html.erb
<div id="error_messages">
  <%= render "shared/error_messages", object: f.object %>
</div>

<div class="form-group">
  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control", required: true %>
</div>

<div class="form-group">
  <%= f.label :description %>
  <%= f.text_area :description, class: "form-control" %>
</div>

<div class="form-group">
  <%= f.label :duration %> <em>(<%= t ".seconds" %>)</em>
  <%= f.text_field :duration, class: "form-control", required: true %>
</div>

<div class="form-group">
  <%= f.label :question_num %>
  <%= f.text_field :question_num, class: "form-control", required: true %>
</div>

<div class="modal-footer">
  <% if f.object.new_record? %>
    <button type="button" class="btn btn-default" data-dismiss="modal"><%= t ".close" %></button>
  <% end %>
  <%= f.submit class: "btn btn-success" %>
</div>

app/views/admin/subjects/_modal.html.erb
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel"><%= t ".create_new_subject" %></h4>
      </div>
      <div class="modal-body">
        <%= form_for [:admin, @subject], remote: true do |f| %>
          <%= render "form", f: f %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/subjects/create.js.erb
<% if @subject.new_record? %>
  $("#error_messages").html("<%= j render 'shared/error_messages', object: @subject %>");
<% else %>
  <% flash[:success] = t ".success" %>
  window.location = "<%= admin_subjects_url %>";
<% end %>

app/views/admin/subjects/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for [:admin, @subject] do |f| %>
      <%= render "form", f: f %>
    <% end %>
  </div>
</div>

app/views/admin/subjects/index.html.erb
<h1><%= t ".list_subjects" %></h1>
<table class="table table-hover">
  <thead>
    <tr>
      <th><%= t ".id" %></th>
      <th><%= t ".name" %></th>
      <th><%= t ".duration" %></th>
      <th><%= t ".question_num" %></th>
      <th><%= t ".created_at" %></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @subjects.each do |subject| %>
      <tr>
        <td><%= subject.id %></td>
        <td><%= subject.name %></td>
        <td><%= subject.duration.to_formatted_s :time %></td>
        <td><%= subject.question_num %></td>
        <td><%= subject.created_at %></td>
        <td><%= link_to t(".edit"), edit_admin_subject_path(subject), class: "btn btn-warning" %></td>
        <td><%= link_to t(".delete"), admin_subject_path(subject),
          method: :delete, data: {confirm: t(".confirm_delete")}, class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
  <%= t ".new_subject" %>
</button>
<%= render "modal" %>