config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  root "exams#index"
  devise_for :users

  resources :users, only: [:show] do
    resources :questions
  end

  resources :exams, except: [:new, :destroy, :edit]

  namespace :admin do
    root "users#index"
    resources :users, except: :show
    resources :subjects, except: [:show, :new]
    resources :exams, only: [:index]
    resources :admin_logs, only: [:index]
    resources :questions
    resources :suggested_questions, only: [:index]
  end

  mount Sidekiq::Web, at: "/sidekiq"
  mount DelayedJobWeb => "/delayed_job"
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_paranoid

  enum role: [:user, :admin]

  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable

  has_many :admin_logs, dependent: :destroy
  has_many :exams, dependent: :destroy
  has_many :questions

  validates :password, presence: true, allow_nil: true

  class << self
    def ransackable_attributes auth_object = nil
      super & ["email", "name", "chatwork_id"]
    end
  end

  def is_user? user
    self == user
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  load_and_authorize_resource

  def index
    @search = @users.search params[:q]
    @users = @search.result
    @search.build_condition
  end

  def new
  end

  def create
    if @user.save
      flash[:success] = t ".success"
      redirect_to admin_users_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update_attributes user_params
      flash[:success] = t ".edit_success"
      redirect_to admin_users_path
    else
      render :edit
    end
  end

  def destroy
    if @user.destroy
      flash[:success] = t ".delete_success"
    else
      flash[:warning] = t ".delete_fail"
    end
    redirect_to admin_users_path
  end

  private
  def user_params
    params.require(:user).permit :email, :name, :chatwork_id, :password,
      :password_confirmation
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]
  def create
    byebug
    super
    if current_user.admin?
      AdminLog.log user: current_user, action: Settings.users.action.login
    end
  end

  def destroy
    byebug
    if current_user.admin?
      AdminLog.log user: current_user, action: Settings.users.action.logout
    end
    super
  end

  protected
  def configure_sign_in_params
    devise_parameter_sanitizer.for(:sign_in) << :attribute
  end
end

app/views/admin/users/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "shared/error_messages", object: @user %>
    <div class="form-group">
      <%= f.label :email %>
      <%= f.text_field :email, class: "form-control", required: true %>
    </div>

    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :chatwork_id %>
      <%= f.text_field :chatwork_id, class: "form-control" %>
    </div>

    <% if f.object.new_record? %>
      <div class="form-group">
        <%= f.label :password %>
        <em>(<%= t ".min_character", parameter: Settings.password.min_character %>)</em>
        <%= f.password_field :password, autocomplete: "off", class: "form-control"%>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation %><br />
        <%= f.password_field :password_confirmation, autocomplete: "off", class: "form-control"%>
      </div>
    <% end %>

    <%= f.submit t(:submit), class: "btn btn-success" %>
  </div>
</div>

app/views/admin/users/edit.html.erb
<h1><%= t ".edit" %></h1>

<%= form_for [:admin, @user] do |f| %>
  <%= render "form", f: f %>
<% end %>

app/views/admin/users/index.html.erb
<h1><%= t ".list_users" %></h1>

<%= search_form_for [:admin, @search], class: "form-inline" do |f| %>
  <%= f.condition_fields do |c| %>
    <%= render "shared/condition_fields", f: c %>
  <% end %>
  <div class="actions"><%= f.submit t("search"), class: "btn btn-primary" %></div>
<% end %>

<%= link_to t(".create_user"), new_admin_user_path, class: "btn btn-success pull-right" %>
<table class="table table-hover">
  <thead>
    <tr class="info">
      <th><%= sort_link @search, :id, t(".id") %></th>
      <th><%= sort_link @search, :name, t(".name") %></th>
      <th><%= sort_link @search, :email, t(".email") %></th>
      <th><%= sort_link @search, :role, t(".role") %></th>
      <th><%= sort_link @search, :chatwork_id, t(".chatwork_id") %></th>
      <th><%= sort_link @search, :created_at, t(".created_at") %></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.role.capitalize %></td>
        <td><%= user.chatwork_id %></td>
        <td><%= user.created_at %></td>
        <td><%= link_to t(".edit"), edit_admin_user_path(user),
          class: "btn btn-primary" %></td>
        <% if user.is_user? current_user %>
          <td></td>
        <% else %>
          <td>
            <%= link_to t(".delete"), [:admin, user],
              method: :delete, data: {confirm: t(".delete_confirm")}, class: "btn btn-danger" %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/users/new.html.erb
<h1><%= t ".new" %></h1>

<%= form_for [:admin, @user] do |f| %>
  <%= render "form", f: f %>
<% end %>