config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  root "exams#index"
  devise_for :users

  resources :users, only: [:show] do
    resources :questions
  end

  resources :exams, except: [:new, :destroy, :edit]

  namespace :admin do
    root "users#index"
    resources :users, except: :show
    resources :subjects, except: [:show, :new]
    resources :exams, only: [:index]
    resources :admin_logs, only: [:index]
    resources :questions
    resources :suggested_questions, only: [:index]
  end

  mount Sidekiq::Web, at: "/sidekiq"
  mount DelayedJobWeb => "/delayed_job"
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <%= t "framgia_test" %>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t("framgia_test"), root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to t("home"), exams_path(current_user) %></li>
          <% if current_user.admin? %>
            <li><%= link_to t(:activity_logs), admin_admin_logs_path %></li>
            <li><%= link_to t(:exams_name), admin_exams_path %></li>
            <li><%= link_to t(:users), admin_users_path %></li>
            <li><%= link_to t(:subjects), admin_subjects_path %></li>
            <% if Rails.env.development? %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <%= t :background_job %><b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to t(:sidekiq), sidekiq_web_path %></li>
                  <li><%= link_to t(:background_job), delayed_job_web_path %></li>
                </ul>
              </li>
            <% end %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <%= t "user.question.question" %><b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to t("user.question.all"), admin_questions_path %></li>
                <li><%= link_to t("user.question.suggested"),
                  admin_suggested_questions_path %></li>
              </ul>
            </li>
          <% else %>
            <li>
              <%= link_to t("contribute_question"), user_questions_path(current_user) %>
            </li>
          <% end %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle nav-avatar" data-toggle="dropdown">
              <%= gravatar_for current_user, size: 40 %>
              <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to t(:my_profile), edit_user_registration_path %></li>
              <li><%= link_to t(:sign_out), destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t(:login), new_user_session_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t "framgia_test" %></title>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": true %>
    <%= javascript_include_tag "application", "data-turbolinks-track": true %>
    <%= csrf_meta_tags %>
    <%= render "layouts/shim" %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
    <%= render "layouts/footer" %>
  </body>
</html>